### ISSUE TITLE
Issue with title on AlightEE

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/spider_web_scraper_jmeker#82]
![image](https://github.com/peviitor-ro/spider_web_scraper_jmeker/assets/41440889/112fdca3-5812-428e-b140-aa023358d1b7)

**Comment by Mede375** [comment]
![image](https://github.com/peviitor-ro/spider_web_scraper_jmeker/assets/144273209/d97c1293-6793-4ad8-a0ea-01e8bd404018)
